ptvsd/wrapper.py
=> Include exception information in stopped event

ptvsd/pydevd/_pydevd_bundle/pydevd_comm.py, ptvsd/pydevd/_pydevd_bundle/pydevd_process_net_command.py, ptvsd/pydevd/pydevd.py, ptvsd/wrapper.py
Adds the ability for PyDev to redirect output when a program is launched for debugging.
=> Ability to redirect output in pydev

ptvsd/wrapper.py
=> add ability to redirect output

ptvsd/ipcjson.py, ptvsd/wrapper.py, tests/__main__.py, tests/helpers/counter.py, tests/helpers/protocol.py, tests/helpers/pydevd/_fake.py, tests/helpers/vsc/_fake.py, tests/helpers/vsc/_vsc.py, tests/ptvsd/highlevel/__init__.py, tests/ptvsd/highlevel/test_lifecycle.py, tests/ptvsd/highlevel/test_messages.py
Recent changes broken the high-level DAP tests. This patch fixes them.
=> Fix highlevel tests.

ptvsd/wrapper.py
=> Preserve file path case on windows for file paths returned

ptvsd/wrapper.py
Raised exceptions:
Uncaught exceptions:
=> ExceptionInfo returns name and description obtained from __exception__ object

ptvsd/wrapper.py
=> revert change introduced in #162

ptvsd/debugger.py
=> Fixes issue with unittests returning boolean exit codes

ptvsd/wrapper.py
=> Checks for isErrorOnEval before responding to evaluate requests

ptvsd/wrapper.py
=> Ensure column number is not 0 in the stackTrace response

ptvsd/wrapper.py
=> Remove breakpoints from files specified in path

ptvsd/wrapper.py
=> Fixes missing hover context issue

ptvsd/wrapper.py
=> Adds evaluateName for variables within containers

ptvsd/wrapper.py
=> Enable set setting values for collection items

ptvsd/debugger.py, ptvsd/ipcjson.py, ptvsd/wrapper.py, tests/helpers/protocol.py, tests/helpers/pydevd/_fake.py, tests/helpers/pydevd/_live.py, tests/helpers/socket.py, tests/helpers/vsc/_fake.py, tests/helpers/workspace.py, tests/highlevel/__init__.py, tests/highlevel/test_live_pydevd.py, tests/highlevel/test_messages.py
This required a bit of refactoring in the testing framework to split off the pydevd-specific parts.
=> Add some initial tests that each use a live pydevd.

tests/highlevel/__init__.py, tests/highlevel/test_messages.py
We we're tracking thread properly, so we were expecting a thread when we shouldn't (but only sometimes, due to dict ordering).
=> Fix intermittent test failures.

ptvsd/futures.py, ptvsd/safe_repr.py, ptvsd/wrapper.py, tests/highlevel/test_messages.py, tests/ptvsd/test_safe_repr.py
Add support for rawString formatting.
Avoid race conditions over shared state when changing value format.
=> Fix #17: Raw value retrieval

ptvsd/debugger.py
=> Insert --module flag before --file

ptvsd/wrapper.py
In this PR:
1. Wait on normal exit and abnormal exit #195
2. Redirect output is now supported #250
=> Support few more debug options from VS

ptvsd/wrapper.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_messages.py
Fixes #245
Waiting for https://github.com/Microsoft/ptvsd/pull/260 to be completed (some overlapping changes).
=> Add support for VSC style debug options

ptvsd/wrapper.py
Handle pydevd message encoding and quoting idiosyncracies on Python 2.
=> Fix #225: UnicodeEncodeError when using tool tips with non ascii characters

ptvsd/wrapper.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_live_pydevd.py, tests/highlevel/test_messages.py
=> Changed default values from strings to booleans in exceptionBreakpointFilters

ptvsd/wrapper.py
=> Handle debug options when attaching

ptvsd/wrapper.py
=> Add FIX_FILE_PATH_CASE to known list of debut_options in _parse_debug_options

ptvsd/pydevd/_pydevd_bundle/pydevd_utils.py, ptvsd/wrapper.py
A bunch of assorted test fixes.
=> Test fixes

ptvsd/wrapper.py
* The version formatted to package style (2.7.14final0). Previously we were returning int string mixed list.
* Removed the user name part from system info
=> Minor fixes to system info

tests/helpers/protocol.py, tests/helpers/pydevd/_fake.py, tests/helpers/pydevd/_pydevd.py, tests/helpers/vsc/_fake.py, tests/highlevel/__init__.py, tests/highlevel/test_live_pydevd.py
We have some races that do not show up on linux (ergo travis).  This patch fixes them.
=> Fix mac tests.

ptvsd/debugger.py
=> Default host name to 127.0.0.1 when launching the debugger via debug function

ptvsd/wrapper.py
=> Fixes an issue with missing frozen frames

README.md, ptvsd/wrapper.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_messages.py
Fixes #322
Also fixed a bug with the parser (`bool` function treats 'False' string as `True`).
=> Pass flag to inicate whether to handle file paths in a case sensitive manner

README.md, ptvsd/wrapper.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_messages.py
=> Rename flag to make it more meaningful

ptvsd/ipcjson.py, tests/helpers/pydevd/_binder.py
=> Don't exit on unknown command

ptvsd/daemon.py
=> No need to kill process if process is already dying

ptvsd/wrapper.py
=> Check if local and remote roots are same, if so then return file path as is

ptvsd/__main__.py, ptvsd/pydevd_hooks.py, ptvsd/runner.py, ptvsd/socket.py, tests/helpers/socket.py, tests/ptvsd/test___main__.py, tests/ptvsd/test_debugger.py
=> Support listening on an external address.

ptvsd/runner.py, ptvsd/wrapper.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_live_pydevd.py, tests/highlevel/test_messages.py, tests/system_tests/test_main.py
=> Implement hit condition breakpoint

ptvsd/pydevd/_pydevd_bundle/pydevd_process_net_command.py
=> Check whether variable is None before checking the length

ptvsd/wrapper.py
=> Fixes KeyError when using DEBUG_STDLIB

ptvsd/wrapper.py, tests/ptvsd/test_internals_filter.py
=> Hiding debugger internals from stack, modules, etc

tests/system_tests/test_schema.py
=> Fix for DownloadCommandTests and CheckCommandTests

Makefile, debugger_protocol/arg/_decl.py, tests/__init__.py, tests/__main__.py, tests/debugger_protocol/__init__.py, tests/helpers/counter.py, tests/helpers/debugclient.py, tests/helpers/debugsession.py, tests/helpers/http.py, tests/helpers/proc.py, tests/helpers/protocol.py, tests/helpers/pydevd/_binder.py, tests/helpers/pydevd/_live.py, tests/helpers/pydevd/_pydevd.py, tests/helpers/threading.py, tests/helpers/vsc/_vsc.py, tests/highlevel/__init__.py, tests/highlevel/test_lifecycle.py, tests/system_tests/test_main.py, tests/system_tests/test_schema.py, tests/test_tests___main__.py
Currently we are only running the ptvsd unit tests under Python 2.  This PR adds in nearly all the rest of the tests.
=> Run most of the tests under Python 2.

ptvsd/wrapper.py
=> Ignore unsupported values in debug options

ptvsd/wrapper.py, tests/highlevel/test_messages.py
=> Handle KeyError while getting or setting variables

ptvsd/wrapper.py, tests/ptvsd/test_internals_filter.py
=> Filter ptvsd files while tracing

ptvsd/_main.py, ptvsd/_vendored/pydevd/_pydev_bundle/pydev_is_thread_alive.py, ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py, ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py, ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py, ptvsd/_vendored/pydevd/pydevd.py, ptvsd/_vendored/pydevd/pydevd_concurrency_analyser/pydevd_concurrency_logger.py, ptvsd/_vendored/pydevd/tests_python/_debugger_case20.py, ptvsd/_vendored/pydevd/tests_python/test_debugger.py, ptvsd/pydevd_hooks.py, ptvsd/runner.py, ptvsd/wrapper.py, tests/helpers/protocol.py, tests/highlevel/__init__.py, tests/highlevel/test_live_pydevd.py, tests/system_tests/test_main.py
=> When a thread is created, notify about it as soon as possible.

ptvsd/ipcjson.py, ptvsd/socket.py, ptvsd/wrapper.py, tests/helpers/debugadapter.py, tests/helpers/socket.py, tests/highlevel/__init__.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_live_pydevd.py, tests/highlevel/test_messages.py, tests/system_tests/test_main.py, tests/test_setup.py
=> Get the tests working on Windows.

DESCRIPTION.md, setup.py
=> Update pypi info

MANIFEST.in
=> Fix for missing Description.md

ptvsd/_vendored/pydevd/pydevd.py
=> Fix for displaying non-user code

ptvsd/wrapper.py
=>  Fix for KeyError in suspended event handle during attach

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py, ptvsd/_vendored/pydevd/pydevd.py, ptvsd/_vendored/pydevd/runfiles.py, ptvsd/_vendored/pydevd/tests_python/_debugger_case_lamda.py, ptvsd/_vendored/pydevd/tests_python/_debugger_case_print.py, ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py, ptvsd/_vendored/pydevd/tests_python/test_debugger.py
Note: also brought some other changes:
- don't list threads marked as pydevd daemon threads
- fix issue hitting lamdas
=> Fixes issues hitting breakpoints multiple times. Fixes #491.

ptvsd/wrapper.py, tests/helpers/debugadapter.py, tests/helpers/debugsession.py, tests/helpers/proc.py, tests/helpers/script.py, tests/highlevel/test_live_pydevd.py, tests/system_tests/test_main.py
(see gh-448)
There is a race between attach and handshake completion that may result in breakpoints not being hit.  This PR fixes that by waiting for handshake completion when waiting for attach.
=> Wait for handshake completion when waiting for attach.

.flake8, .flake8.ci, Makefile, README.md, debugger_protocol/schema/UPSTREAM, debugger_protocol/schema/debugProtocol.json, tests/__main__.py, tests/system_tests/test_main.py, tests/test_tests___main__.py
Switch output formats/calling conventions to match expectations best from VSTS CI point of view.
=> Update for VSTS-based CI process

.travis.yml, ptvsd/_util.py, ptvsd/wrapper.py, setup.py, tests/debugger_protocol/schema/test___main__.py, tests/system_tests/test_schema.py
@huguesv  and I were testing compatibility to ensure we have the right information for PTVS. During the experimentation we found that 3.4 almost worked. This PR includes some of the fixes that were needed to get `ptvsd` working with python 3.4.
=> Compatibility python 3.4

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py, ptvsd/_vendored/pydevd/_pydevd_frame_eval/pydevd_frame_tracing.py, ptvsd/wrapper.py, tests/highlevel/test_live_pydevd.py, tests/highlevel/test_messages.py
=> Fix log points on Python 2.7

ptvsd/wrapper.py, tests/highlevel/test_live_pydevd.py, tests/system_tests/test_main.py
=>  Fixes issue where multiple thread created events were sent for the same thread

.travis.yml, ptvsd/wrapper.py, tests/highlevel/test_live_pydevd.py
=> Enable debugging of files wth unicode chars in Py2.7

ptvsd/__main__.py, ptvsd/_local.py, tests/helpers/argshelper.py, tests/ptvsd/test___main__.py, tests/ptvsd/test_debugger.py, tests/ptvsd/test_local.py
1. Fixes #540 
2. Adds no-debug tests #547
=> Fixes and tests for no-debug run

tests/helpers/debugsession.py, tests/helpers/message.py, tests/system_tests/__init__.py, tests/system_tests/test_launch.py, tests/system_tests/test_main.py
=> Add await for easier testing

tests/helpers/debugadapter.py, tests/system_tests/test_attach.py
Also fixed issue causing connection errors tests
=> System tests for basic attach

ptvsd/wrapper.py, tests/highlevel/test_messages.py
=> Add 'evaluateName' to top level variables

tests/helpers/debugadapter.py, tests/helpers/debugclient.py, tests/highlevel/test_lifecycle.py
=> Wait for socket server before connecting in Tests

tests/highlevel/test_lifecycle.py, tests/system_tests/test_attach.py
* Fixes for to account for just my code changes
* Workaround for broken attach in ptvsd
=> Some more fixes to broken tests

tests/system_tests/test_variables.py
=> Add tests to verify variable sorting

ptvsd/_remote.py
=> Fixes a bug that forced host to always be localhost.

tests/__init__.py, tests/helpers/__init__.py, tests/helpers/debugadapter.py, tests/helpers/debugclient.py, tests/helpers/debugsession.py, tests/helpers/proc.py, tests/helpers/resource.py, tests/helpers/socket.py, tests/helpers/workspace.py, tests/system_tests/__init__.py, tests/system_tests/test_basic.py, tests/system_tests/test_breakpoints.py, tests/system_tests/test_exceptions.py, tests/system_tests/test_main.py, tests/system_tests/test_remote.py, tests/system_tests/test_restart_vsc.py, tests/system_tests/test_schema.py, tests/system_tests/test_variables.py
The system tests have a number of minor formatting and structural issues that would be better to clean up sooner rather than later.  This PR addresses nearly all of them.
=> A bunch of cleanup/lint fixes for the system tests.

.gitignore, ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py, ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py, ptvsd/_vendored/pydevd/tests_python/test_debugger.py, ptvsd/_vendored/pydevd/tests_python/test_in_project_roots.py
The code now checks for the case where virtualenv is inside the workspace and vice-versa.
=> Fixed #481: JustMyCode debugging not working in VS Code when virtualenv is inside workspace.

debugger_protocol/schema/UPSTREAM
=> Update upstream metadata for debug protocol

tests/highlevel/__init__.py, tests/highlevel/test_live_pydevd.py
=> Wait for program to run to completion to fix issue with live exception tests

tests/system_tests/test_misc.py
=> Add test with no output

ptvsd/_remote.py
=> Fix for attach to remote machine

ptvsd/wrapper.py, tests/resources/system_tests/test_misc/mymod/__main__.py, tests/resources/system_tests/test_misc/stoponentry.py, tests/system_tests/test_misc.py
=> Enable stop on entry feature

ptvsd/wrapper.py, tests/highlevel/__init__.py, tests/highlevel/test_lifecycle.py, tests/system_tests/test_web_frameworks.py
=> Fixes some bugs with just-my-code

ptvsd/wrapper.py
=> Clean up template breakpoints on detach

ptvsd/runner.py
@DonJayamanne do we really need this time out since we no longer do output polling?
=> Remove redirect output timeout

tests/system_tests/test_exceptions.py
=> Restore some test code

ptvsd/_vendored/pydevd/pydevd.py, ptvsd/_vendored/pydevd/pydevd_file_utils.py
Addresses #617 
@fabioz I am not sure if this is the right fix for the problem. Let me know if I need to make changes in other places.
=> Add file path to sys.argv when running as module

ptvsd/attach_server.py, ptvsd/wrapper.py, tests/helpers/proc.py, tests/resources/system_tests/test_break_into_debugger/attach_test.py, tests/resources/system_tests/test_break_into_debugger/launch_test.py, tests/resources/system_tests/test_break_into_debugger/reattach_test.py, tests/system_tests/test_break_into_debugger.py
Fixes: #714, #715, #716, #717
Fixes: #712 
Note: #706 had not fixed #712
=> break_into_debugger fixes and tests

setup.py
=> Change release type from alpha to production

ptvsd/wrapper.py, tests/resources/system_tests/test_misc/returnvalues.py, tests/system_tests/test_misc.py
Add `ShowReturnValue` in debug options to enable this feature.
#420
=> Show return values

tests/system_tests/test_disconnect.py
=> Enable more disconnect tests

ptvsd/wrapper.py, tests/resources/system_tests/test_wait_on_exit/waitonexit.py, tests/system_tests/test_wait_on_exit.py
=> Add test cases for wait on exit

ptvsd/socket.py
=> Change arg to socket.listen from 0 to 1

ptvsd/pathutils.py
=> Fixes index error caused when debugging python files on network drives.

README.md
=> Update readme with usage details

ptvsd/wrapper.py
=> for VS client only send single stopped event in multi-threaded case

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, ptvsd/wrapper.py, tests/resources/system_tests/test_misc/output_test.py, tests/system_tests/test_misc.py
=>  Preserve tab character while parsing XML

ptvsd/_local.py
=> Check if exit code is none before converting to int

ptvsd/wrapper.py, tests/highlevel/test_messages.py
=> Add messages to error responses

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, test_requirements.txt
=> Updating contribution details

Makefile, ptvsd/__main__.py, ptvsd/_util.py, ptvsd/messaging.py, ptvsd/multiproc.py, ptvsd/pydevd_hooks.py, ptvsd/socket.py, ptvsd/wrapper.py, pytest.ini, pytests/conftest.py, pytests/func/test_multiproc.py, pytests/helpers/__init__.py, pytests/helpers/backchannel.py, pytests/helpers/messaging.py, pytests/helpers/pattern.py, pytests/helpers/session.py, pytests/helpers/timeline.py, pytests/helpers/watchdog.py, pytests/requirements.txt, setup.py, test_requirements.txt
+ tests, and numerous test framework fixes and additions for those tests!
=> Fix #811: new socket server to receive pid and port for subprocesses

pytests/conftest.py
=> Don't add additional new line with @pyfile

ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey_qt.py
Updating `ptvsd` with external contribution to `pydevd`.
=> Add support for monkey-patching pyside2.

ptvsd/wrapper.py, tests/helpers/pydevd/_messages.py, tests/highlevel/__init__.py, tests/highlevel/test_lifecycle.py, tests/highlevel/test_messages.py
=> Undefined variable error in breakpoint condition

.flake8, ptvsd/__main__.py, ptvsd/messaging.py, ptvsd/multiproc.py, ptvsd/options.py, ptvsd/run_code.py, pytest.ini, pytests/conftest.py, pytests/func/test_run.py, pytests/helpers/colors.py, pytests/helpers/session.py, pytests/helpers/test_timeline.py
=> Fix #886: ptvsd command line should support the equivalent of python -c

ptvsd/wrapper.py, pytests/test_socket.py
=>  Add socket reuse tests

ptvsd/wrapper.py, tests/system_tests/test_main.py
=> Fix to preserve frame and variable ids while stepping

ptvsd/__main__.py, ptvsd/daemon.py, ptvsd/messaging.py, ptvsd/multiproc.py, ptvsd/options.py, ptvsd/pydevd_hooks.py, ptvsd/socket.py, ptvsd/wrapper.py, pytests/func/test_multiproc.py, pytests/helpers/session.py, pytests/helpers/timeline.py, pytests/test_messaging.py, tests/highlevel/test_messages.py, tests/ptvsd/test_socket.py
This completes the implementation of multiprocess debugging for all cases.
=> #425: Auto-attach to sub process (auto-reload of Django, Flask) 

pytests/conftest.py, pytests/func/test_django.py, pytests/func/test_flask.py, pytests/func/test_run.py, pytests/func/testfiles/django1/app.py, pytests/func/testfiles/django1/templates/hello.html, pytests/func/testfiles/flask1/app.py, pytests/func/testfiles/flask1/templates/hello.html, pytests/func/testfiles/testroots.py, pytests/helpers/pathutils.py, pytests/helpers/session.py, pytests/helpers/timeline.py, pytests/helpers/webhelper.py
=> pytests for django and flask

pytests/func/test_multiproc.py
#892
Added a basic test for multiproc using subprocess lib
=> Add subprocess library test

ptvsd/multiproc.py, ptvsd/pydevd_hooks.py, ptvsd/wrapper.py, pytests/func/test_django.py, pytests/func/test_flask.py, pytests/helpers/session.py
=> Add 'Multiprocess' debug option 

debugger_protocol/schema/file.py, debugger_protocol/schema/metadata.py, debugger_protocol/schema/upstream.py, ptvsd/wrapper.py, pytests/func/test_evaluate.py, pytests/func/test_start_stop.py, pytests/helpers/session.py, tests/helpers/debugclient.py, tests/highlevel/test_live_pydevd.py
Tests for break on start,  wait for normal and abnormal exit
=> Tests for break on start,  wait for normal and abnormal exit

pytests/conftest.py, pytests/func/test_breakpoints.py, pytests/func/test_completions.py, pytests/func/test_django.py, pytests/func/test_evaluate.py, pytests/func/test_flask.py, pytests/func/test_multiproc.py, pytests/func/test_run.py, pytests/func/test_start_stop.py, pytests/helpers/session.py, pytests/helpers/timeline.md
=> Decouple debug session and start method

README.md
Correct Grammatical Mistake Hence make it good look for reader
=> Correct Grammatical Mistakes

ptvsd/wrapper.py
=> Empty stack traces. Fixes #1006

Makefile, pytests/conftest.py, pytests/func/test_breakpoints.py, pytests/func/test_completions.py, pytests/func/test_django.py, pytests/func/test_flask.py, pytests/func/test_multiproc.py, pytests/func/test_start_stop.py, pytests/helpers/session.py, pytests/helpers/timeline.py, pytests/helpers/watchdog.py, test_requirements.txt
Various stuff that came up while trying to debug #987 (but no fix for the actual issue so far).
=> Test fixes and tweaks

pytests/test_debugger.py
=> Remove references to old test code in test_debugger.py

pytests/test_debugger.py
=> Merge into master

pytests/conftest.py, pytests/func/test_breakpoints.py, pytests/func/test_completions.py, pytests/func/test_django.py, pytests/func/test_evaluate.py, pytests/func/test_flask.py, pytests/func/test_multiproc.py, pytests/func/test_run.py, pytests/func/test_start_stop.py, pytests/helpers/session.py, pytests/helpers/test_timeline.py, pytests/helpers/timeline.py
And other test improvements.
Fixes #1025, Fixes #1026, Fixes #1027
=> Fix #1025, #1026, #1027 + workaround for #1028

pytests/conftest.py, pytests/func/test_args.py, pytests/func/test_break_into_dbg.py, pytests/func/test_breakpoints.py, pytests/func/test_evaluate.py, pytests/func/test_output.py, pytests/func/test_threads.py, pytests/helpers/session.py, pytests/test_debugger.py, pytests/test_internals_filter.py, pytests/test_modules_manager.py, pytests/test_parse_args.py, pytests/test_pathutils.py
=> Migrate functional tests: part 1

pytests/func/test_breakpoints.py, pytests/func/test_evaluate.py, pytests/func/test_exception.py
=> More pytests

pytests/func/test_attach.py, pytests/func/test_break_into_dbg.py, pytests/func/test_breakpoints.py, pytests/func/testfiles/attach/attach1.py, pytests/helpers/session.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py, src/ptvsd/_vendored/pydevd/_pydevd_frame_eval/pydevd_frame_tracing.py, src/ptvsd/wrapper.py
=> Tests and fixes

src/ptvsd/exit_handlers.py
=> Fixes AttributeError in exit handler when using jython.

src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_base_schema.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_json_debug_options.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_xml.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_xml.py, src/ptvsd/_vendored/pydevd/pydevd.py, src/ptvsd/_vendored/pydevd/pydevd_tracing.py, src/ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/wrapper.py
Added partial support for options (on attach/launch), disconnect (removes breakpoints and run all threads) and set breakpoints.
=> Extracted pydevd API and using DAP for some messages.

src/ptvsd/wrapper.py, tests/func/test_path_mapping.py
=> Map '.' in remoteRoot to current working dir

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py
@karthiknadig this should fix the issue, but unfortunately I won't have time to do new tests for this today... (I'll leave it up to you on whether you want to put as is, include tests yourself or wait for me to do it tomorrow).
=> Remove breakpoints from all mappings. Fixes #1126

src/ptvsd/__main__.py, src/ptvsd/_remote.py, src/ptvsd/pydevd_hooks.py, tests/func/test_run.py, tests/helpers/session.py
=> Fix #1125: No-Debug run (ctrl+F5) VSCode is unable to establish connection with debugger

src/ptvsd/__main__.py, tests/func/test_attach.py, tests/helpers/session.py
=> Add test for attach using pid

tests/func/test_django.py, tests/func/test_flask.py, tests/func/testfiles/django1/app.py, tests/func/testfiles/django1/templates/bad.html, tests/func/testfiles/flask1/app.py, tests/func/testfiles/flask1/templates/bad.html
=> Add more tests 

src/ptvsd/__main__.py
=> Ensure we listen for subprocess if --multiprocess flag is used.

tests/func/test_attach.py, tests/helpers/session.py
=> Enable reattach test with fixes

src/ptvsd/_util.py, src/ptvsd/_vendored/force_pydevd.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py, src/ptvsd/_vendored/pydevd/pydevd.py, src/ptvsd/messaging.py, src/ptvsd/wrapper.py, tests/func/test_step.py
Currently blocked by https://github.com/Microsoft/ptvsd/issues/1163, so not enabling this yet.
=> Fix #18: Set Next Statement

src/ptvsd/wrapper.py, tests/func/test_breakpoints.py
=> Enable delayed stack trace loading

tests/func/test_justmycode.py
=> Add test for jmc stack frames

pytest.ini, src/ptvsd/__main__.py, src/ptvsd/_local.py, src/ptvsd/_remote.py, src/ptvsd/_util.py, src/ptvsd/attach_server.py, src/ptvsd/daemon.py, src/ptvsd/futures.py, src/ptvsd/ipcjson.py, src/ptvsd/log.py, src/ptvsd/messaging.py, src/ptvsd/multiproc.py, src/ptvsd/options.py, src/ptvsd/pydevd_hooks.py, src/ptvsd/session.py, src/ptvsd/wrapper.py, tests/helpers/debuggee/backchannel.py, tests/helpers/messaging.py, tests/helpers/session.py, tox.ini
Implement logging framework, and use that in place of existing ad-hoc logging.
=> Fix #890: Provide option to enable logging

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_suspended_frames.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_local_variables_hex.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/_vendored/pydevd/tests_python/test_resolvers.py, tests/func/test_evaluate.py
Fixes #1174, Fixes #1207
@fabioz what is a convenient place to add the variables test for the json work in pydevd?
=> Fixes #1174. Ensure keys are in hex for dicts, lists, tuples

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_evaluate.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/wrapper.py
=> Fixes exception shown when exec throws exception. Fixes #1234

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_xml.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_deep_stacks.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/wrapper.py
=> Move stack levels to pydevd.

src/ptvsd/_util.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_adjust_breakpoint.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/wrapper.py
=>  Move breakpoint validation into pydevd. Fixes #1335

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/wrapper.py
=> Move path mapping setup into pydevd. Fixes #1359

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/wrapper.py, tests/func/test_path_mapping.py
=> Move source request to pydevd. Fixes #1333

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/wrapper.py
=> goto response via DAP. Fixes #1343. 

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py, tests/conftest.py, tests/func/test_stop_on_entry.py
=> Ensure stop_on_entry is unset after first break. Fixes #1456

src/ptvsd/common/messaging.py, tests/test_messaging.py
Add support for "yield" in request handlers.
=> Fix #1502: Concurrent DAP request processing

src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/debugProtocolCustom.json, src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_schema.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/wrapper.py, tests/func/test_system_info.py
This is a bit of information that we need for the debug server.
=> Add systeminfo to pydevd

src/ptvsd/adapter/messages.py
Fix #1491, Fix #1492, Fix #1493
=>  Migrate bunch of requests, Fix #1491, Fix #1492, Fix #1493

README.md
=> Update debugOptions in docs

.gitignore, .vscode/launch.json, src/ptvsd/adapter/__main__.py, src/ptvsd/adapter/channels.py, src/ptvsd/adapter/messages.py, src/ptvsd/adapter/state.py
Fix and refactor debugServer mode for ptvsd.adapter.
Add launch.json for convenient testing of ptvsd.adapter.
Various minor fixes.
=> debugServer fixes

src/ptvsd/common/launcher.py, tests/ptvsd/common/test_launcher.py
=> Add launcher script that handles wait-on-* feature

.github/CODEOWNERS, src/ptvsd/__init__.py, src/ptvsd/__main__.py, src/ptvsd/adapter/__main__.py, src/ptvsd/adapter/channels.py, src/ptvsd/adapter/contract.py, src/ptvsd/adapter/messages.py, src/ptvsd/adapter/options.py, src/ptvsd/common/json.py, src/ptvsd/common/log.py, src/ptvsd/common/messaging.py, src/ptvsd/debugger.py, src/ptvsd/server/__main__.py, tests/ptvsd/common/test_launcher.py
=>  Fix #1612: Parse and expose DAP capabilities

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py, tests/helpers/session.py
=> Ensure stopped on goto changes focus

src/ptvsd/adapter/debuggee.py, src/ptvsd/adapter/messages.py, tests/ptvsd/common/test_launcher.py
=>  Attach to pid support

src/ptvsd/adapter/debuggee.py, src/ptvsd/common/attach_script_ptvsd_pid.py, src/ptvsd/server/attach_pid_injected.py, src/ptvsd/server/main.py, tests/ptvsd/server/test_attach.py, tests/start_methods.py
=> Fix for attach to pid tests

tests/ptvsd/server/test_breakpoints.py, tests/ptvsd/server/test_exception.py, tests/ptvsd/server/test_multiproc.py, tests/ptvsd/server/test_source_mapping.py, tests/ptvsd/server/test_system_info.py, tests/ptvsd/server/test_threads.py, tests/ptvsd/server/test_tracing.py
=> Move new tests from master to refactor branch

tests/colors.py, tests/helpers.py, tests/printer.py, tests/ptvsd/server/test_tracing.py
the tests folder is getting crowded with helpers. Will do a separate PR moving them into their own sub package.
=> Fixes and move more helpers.

src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py, src/ptvsd/_vendored/pydevd/pydevd.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_no_subprocess_patching.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py
The api is:
```
import pydevd
with pydevd.skip_subprocess_arg_patch():
...
```
=> Provide api to launch python executable without subprocess patching. Fixes #1711

.vscode/launch.json, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, src/ptvsd/_vendored/pydevd/pydevd.py, src/ptvsd/adapter/__main__.py, src/ptvsd/adapter/ide.py, src/ptvsd/adapter/server.py, src/ptvsd/server/api.py
Fixes #1783
Fixes #1766
Fixes #1712
I made a temp solution to #1783.
=> enable_attach should spawn adapter

src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/debugProtocolCustom.json, src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_schema.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py
=> Add ppid to PydevdProcessInfo

src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_console_utils.py, src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py, src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey_qt.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_cython.c, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_cython.pyx, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_dont_trace_files.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_kill_all_pydevd_threads.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_xml.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py, src/ptvsd/_vendored/pydevd/_pydevd_frame_eval/pydevd_frame_tracing.py, src/ptvsd/_vendored/pydevd/pydevd.py, src/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_script.py, src/ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case17a.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/_vendored/pydevd/tests_python/tests_single_notification.py
Note that in this request I've also done changes to improve the shutdown procedure to avoid abruptly closing the socket -- although note that this should only improve the situation, not fix it completely (i.e.: things like https://github.com/microsoft/ptvsd/issues/1813 can still happen -- this wasn't really the main point of this pull request).
I'll take a look at https://github.com/microsoft/ptvsd/issues/1813 afterwards.
=> Make it possible to reconnect on attach to pid. Fixes #1760

packaging/win/sign.proj
Fix for #2028
/cc @fabioz, @int19h
=> Add inject exe to the signing project.

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_breakpoints.py, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_cython.c, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_cython.pyx, src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py, src/ptvsd/_vendored/pydevd/pydevd.py, src/ptvsd/_vendored/pydevd/pydevd_file_utils.py, src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_unhandled_just_my_code.py, src/ptvsd/_vendored/pydevd/tests_python/test_convert_utilities.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger.py, src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py, src/ptvsd/_vendored/pydevd/third_party/cython_json.py, src/ptvsd/_vendored/pydevd/third_party/tests_cython_json.py, tests/ptvsd/server/test_exclude_rules.py
This commit also makes sure that unhandled exceptions raised in libraries are shown if some frame from its stack is in user code (when justMyCode:true).
=> Consider relative paths as library paths. Fixes #1946 Fixes #2027

src/ptvsd/adapter/__main__.py, src/ptvsd/server/api.py
Fix ptvsd.adapter to respect the --host command-line switch again.
=> Fix #2038: Unable to attach docker with version 5
