ptvsd/pathutils.py
ptvsd/wrapper.py
tests/ptvsd/test_pathutils.py

Fixes #88 
@int19h 
I had to revert the change where we were setting the `os_id` to `UNIX` even on `Widows OS`.
This was because breakpoints didn't work at all on Windows for Visual Studio (#163).
However breakpoints continued to work for VS Code.
**We have two solutions:**
1. Ensure `os_id` is always set to `UNIX` for VS Code (on all OS).
However in light of the recent issue in VS (#163), I'm tempted not to go down this path. 
Its better to have duplicate editors than not having breakpoints being hit at all. Who knows what else could break.
2. The solution in the PR
Not elegant, but i believe this is the safest, at least until we fully understand why changing `os_id` to 'UNIX` caused breakpoints to fail on Windows for VS and NOT for VSCode.
Possibly because the breakpoints were sent to …

Fix file path case on windows

---

ptvsd/wrapper.py

In some situations xml.thread.frame isn't treated as a list (for lookup purposes).  Explicitly converting to a list fixes the problem.

Fix on_pydevd_thread_suspend().

---

ptvsd/wrapper.py
tests/helpers/socket.py
tests/highlevel/__init__.py
tests/highlevel/test_messages.py

This ensures that we remember to add tests when adding support for a request or event.

Add tests for unsupported requests and events.

---

ptvsd/wrapper.py

Couple of fixes

---

ptvsd/untangle.py

Fixes #119
Fixes #186
`untangle` puts the entire XML returned by `pydevd` in the `os.path.exists()` check. This breaks when the XML is especially large like the one returned by expanding `sys.modules`

Fixes path too long bug when expanding large collections

---

ptvsd/safe_repr.py
ptvsd/wrapper.py

Fixes #198
sample code:
```
lines = [1234, 0, 1, 10, 16, 23, 32]
records = {1: [12,13,14,15,16], 10: [120,130,140,150]}
```
Hex display:
Long integers:

Support display in hex

---

MANIFEST.in
ptvsd/pydevd/_pydevd_bundle/pydevd_frame.py
setup.py
win/build_all.ps1
win/packages.config
win/sign.proj

This script can be run to generate a semi-pure wheel that includes precompiled extension modules for 3.5 and 3.6, both 32-bit and 64-bit. (Python 3.5 is when Windows started using ABI suffix on extension modules - we can't replicate this as easily for earlier versions.) I already have an internal build definition using this that can also sign all the binaries as needed.
I also fixed #112 by changing how we build the extension modules (i.e. with the correct names). I'm also not quite sure why the `default_return_value` change became necessary, but it was, so I assume it was one of our patches?

Enable build and sign on Windows

---

ptvsd/wrapper.py

This change is part of the debug REPL changes needed for VS

Do eval and exec for repl evaluate requests

---

ptvsd/wrapper.py

Fixes #228 
I believe its safe to just ignore all errors when shutting down & releasing resources.
At the moment, the error is `socket.error`.
Its very difficult to replicate this issue (was able to replicate it consistently earlier today).

Ignore errors when closing the socket

---

ptvsd/wrapper.py
tests/highlevel/test_messages.py

In this PR:
1. Parse launch options sent by VS
2. Enable Django and Jinja2 template debugging for VS
Notes:
For VS flask project we have to enable breakpoints in flask project, and send `FLASK_DEBUG=True` as debug option.
Pending:

Enable Django for VS

---

ptvsd/wrapper.py
tests/helpers/socket.py
tests/highlevel/__init__.py
tests/highlevel/test_lifecycle.py
tests/highlevel/test_live_pydevd.py

Provide a telemetry message incorporating ptvsd version in response to initialization request.
Add a custom message for more detailed information about ptvsd and its environment.

Fix #193: Capture usage of the experimental debugger

---

ptvsd/wrapper.py
tests/helpers/protocol.py
tests/helpers/pydevd/_binder.py
tests/helpers/pydevd/_fake.py
tests/helpers/pydevd/_live.py
tests/helpers/vsc/_fake.py
tests/highlevel/__init__.py
tests/highlevel/test_lifecycle.py
tests/highlevel/test_live_pydevd.py
tests/highlevel/test_messages.py

With some of the changes in the last few weeks we introduces a couple of race conditions in the functional tests.  This patch addresses those by shuffling some operations around and putting locks in the right places.  There might be one or two more races left in the test code but they are pretty infrequent.

Fix races in test code.

---

ptvsd/__init__.py
ptvsd/__main__.py
ptvsd/debugger.py
ptvsd/wrapper.py
tests/__init__.py
tests/helpers/pydevd/_live.py

This change is intended to accommodate future work (adding more CLI options where using the launch config is insufficient).  It also allows us to define a consistent and easy-to-discover CLI, independent of PyDevd.
To be backward compatible, the code also supports the PyDevd CLI (for now).

Add explicit CLI handling for ptvsd.

---

ptvsd/__main__.py
ptvsd/debugger.py
tests/ptvsd/test___main__.py
tests/ptvsd/test_debugger.py

PR #266 inadvertently introduced some backward-incompatible changes to how the ptvsd CLI works.  This PR fixes them.
I've also added a number of unit tests.  In a follow-up PR I'll be adding some full-stack tests using sockets and subprocess.
(should resolve #292, #299, #302, and (partially) #301)

Fix problems with running ptvsd.

---

ptvsd/wrapper.py

Do not stop on exit if attaching, or if disconnect request has been received.

Fix #319: VS "Stop Debugging" triggers "Press any key to continue"

---

README.md
ptvsd/wrapper.py
tests/highlevel/test_messages.py

Fixes #318
This is an opt in feature.
We'll be enabling this as a default feature in VSC.
* If users provide source mappings then, that wins over source references.
* If users do not provide source mappings, then source references are used
* If user provides source mappings, but PTVSD is unable to map the files (e.g. standard lib code), then source references are used

Add support for remote source references

---

ptvsd/wrapper.py
tests/highlevel/__init__.py
tests/highlevel/test_lifecycle.py
tests/highlevel/test_live_pydevd.py
tests/system_tests/test_main.py

This guarantees that the `output` message is always sent first.

Wait until the end of VSCodeMessageProcessor.start() to start handling incoming messages.

---

ptvsd/_vendored/__init__.py
ptvsd/_vendored/force_pydevd.py
ptvsd/wrapper.py

Terminate the process immediately instead of closing pydevd socket when disconnecting after launch.
(fixes #325)

Fix #325: Debuggee no longer terminates

---

ptvsd/_main.py
ptvsd/_util.py
ptvsd/daemon.py
ptvsd/exit_handlers.py
ptvsd/ipcjson.py
ptvsd/pydevd_hooks.py
ptvsd/runner.py
ptvsd/session.py
ptvsd/socket.py
ptvsd/wrapper.py
tests/helpers/__init__.py
tests/helpers/_io.py
tests/helpers/counter.py
tests/helpers/debugadapter.py
tests/helpers/debugclient.py
tests/helpers/debugsession.py
tests/helpers/lock.py
tests/helpers/proc.py
tests/helpers/protocol.py
tests/helpers/pydevd/_binder.py
tests/helpers/pydevd/_live.py
tests/helpers/socket.py
tests/highlevel/test_live_pydevd.py
tests/ptvsd/test___main__.py
tests/ptvsd/test_socket.py
tests/system_tests/test_connection.py
tests/system_tests/test_main.py

(fixes #208)
> [WIP]  This is mostly done.  There's one failing test (`tests.highlevel.test_live_pydevd.LogpointTests`), which has to do with how a session connection is closed.  Once that is resolved this should be good to go.
Currently when ptvsd starts up (as server) it listens for a connection and shuts down when the debug session is done.  This prevents re-attach.  To fix this we go back to listening for a connection after getting a "disconnect" (or the client closes the connection).

Support re-attaching to an adapter.

---

ptvsd/wrapper.py
tests/highlevel/__init__.py
tests/highlevel/test_messages.py

Fixes #349
The change here is to request all threads to be suspended. This is different from suspend policy, which is what we need for breakpoints to suspend all thread when a breakpoint is hit.

Suspend all threads on pause

---

ptvsd/safe_repr.py

Fixes exception in django cause by long iter check

---

ptvsd/daemon.py
ptvsd/pydevd_hooks.py
ptvsd/runner.py
ptvsd/session.py
ptvsd/wrapper.py
tests/helpers/debugclient.py
tests/system_tests/test_main.py

(fixes gh-464)
The code in ptvsd/runner.py was originally copied from elsewhere and slightly adapted.  Over time the APIs diverged, which lead to the failure in gh-464.  This PR fixes the problem by getting rid of the code duplication.

Remove code duplication in runner.py.

---

ptvsd/_util.py
ptvsd/daemon.py
ptvsd/session.py
ptvsd/wrapper.py
tests/helpers/debugclient.py
tests/helpers/debugsession.py
tests/helpers/http.py
tests/helpers/protocol.py
tests/helpers/pydevd/_binder.py
tests/helpers/pydevd/_fake.py
tests/helpers/pydevd/_live.py
tests/helpers/threading.py
tests/highlevel/__init__.py
tests/highlevel/test_lifecycle.py
tests/highlevel/test_live_pydevd.py
tests/system_tests/test_main.py

(fixes gh-459)
We must wait-for-user before the "disconnect" response is sent.  This PR fixes that.

Wait-on-exit before sending "disconnect" response.

---

ptvsd/_util.py
ptvsd/daemon.py
ptvsd/session.py
ptvsd/wrapper.py
tests/highlevel/__init__.py
tests/highlevel/test_lifecycle.py
tests/highlevel/test_live_pydevd.py
tests/system_tests/test_main.py

(fixes gh-459)
Our exit handling was all over the place.  I've refactored the code to properly separate concerns.  One consequence is that this fixes wait-on-exit.

Handle exit explicitly.

---

tests/ptvsd/test_pathutils.py

(fixes gh-243)
Under some corner cases the tests for pathutils fail, due to how Python's import system does not resolve casing on filenames.  This PR fixes that.

Check against the actual filename in pathutils tests.

---

ptvsd/wrapper.py

What happened was that the debugger exited and stopped tracing because of the exception.

No longer raising UnsupportedPyDevdCommandError when stdin input is requested. Fixes #490

---

ptvsd/wrapper.py
tests/highlevel/test_messages.py

(fixes #512)
The XML library we are using treats a single-item list as a single item instead of a list.  This breaks `on_stackTrace()`.  This PR fixes the problem by converting `xframes` to a list before checking its size.

GH-512: Fix single-frame stack trace handling.

---

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py
ptvsd/_vendored/pydevd/pydevd.py
ptvsd/_vendored/pydevd/pydevd_tracing.py
ptvsd/_vendored/pydevd/runfiles.py
ptvsd/_vendored/pydevd/tests_python/_debugger_case_settrace.py
ptvsd/_vendored/pydevd/tests_python/test_debugger.py
ptvsd/attach_server.py

This patch makes sure that:
- When a thread is suspended the stepping function is properly set (otherwise it may end up not breaking if the function was previously cached to be skipped).
- pydevd threads are not traced even if the tracing function is set on them.
- Changes settrace to let users pass where exactly the tracing should pause and use that API to make the pause from ptvsd as the previous approach had some issues if a given function had been previously skipped and currently had no tracing set.

Fix for #501 and #479 (issues related to pausing a thread with debugger.set_suspend)

---

tests/system_tests/test_main.py

Remove the `skipUnless` condition I introduced in a prior PR.

Re-enable disabled test from prior PR

---

ptvsd/_remote.py
ptvsd/_util.py
ptvsd/attach_server.py
ptvsd/daemon.py
ptvsd/pydevd_hooks.py
ptvsd/session.py
ptvsd/wrapper.py
tests/__main__.py
tests/helpers/debugclient.py
tests/helpers/debugsession.py
tests/helpers/http.py
tests/helpers/proc.py
tests/helpers/protocol.py
tests/highlevel/__init__.py
tests/system_tests/test_main.py

(fixes #448)
While #502 helped with the race between enable_attached() and adding breakpoints, there was still a small race left.  This PR fixes it by CMD_RUN is not issued until after the breakpoints have been added.
This PR will also have an impact on #285, #460, and #472, though it might not resolve them completely.

Add breakpoints before CMD_RUN is issued.

---

ptvsd/_vendored/pydevd/_pydevd_frame_eval/pydevd_frame_tracing.py

Note: this broke with the latest logpoint integration (this path is not actually active right now because frame evaluation needs work before it can be made active).

Add missing 'import os'.

---

ptvsd/daemon.py
ptvsd/wrapper.py
tests/helpers/pydevd/_binder.py

(see #530)
os.kill() terminates the process immediately.  However, we need the "disconnect" response to be sent (indirectly via the atexit handler).  This PR switches to sys.exit() solve the problem.

Use sys.exit() instead of os.kill().

---

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py
ptvsd/_vendored/pydevd/pydevd_file_utils.py
ptvsd/_vendored/pydevd/tests_python/_debugger_case_path_translation.py
ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
ptvsd/_vendored/pydevd/tests_python/test_convert_utilities.py

This patch makes improvements in the path handling in pydevd.
It doesn't completely fix https://github.com/Microsoft/ptvsd/issues/333 because the behavior there is expected (the path separators are always sent to be compatible with the client), still, it fixes the `CMD_LOAD_SOURCE` so that translation happens there properly and the case of files should now be correct on windows.
Hopefully it also fixes https://github.com/Microsoft/ptvsd/issues/473 (although I haven't actually tested that it does so).

Fix issues related to path translations and case of files seen on client.

---

ptvsd/wrapper.py
tests/highlevel/test_messages.py

Fixes #518
Previously:
With the fix:

Handle multi-line console commands.

---

tests/__main__.py

The -v verbosity switch is not being respected on VSTS when we run tests.
The XMLTestRunner we are using to produce VSTS-compatible JUnit test output logs doesn't respect the -v switch being sent into the unittest process.
When junit report file is being generated, detect if the -v or --verbose switch is being applied. If it is, set the verbosity to '2' in the XMLTestRunner.

Update verbosity when we create junit-style output report files

---

tests/system_tests/test_basic.py
tests/system_tests/test_breakpoints.py
tests/system_tests/test_exceptions.py
tests/system_tests/test_variables.py

Purpose: Avoid having to use `@unittest.skip`
* Create base classes for tests
* Move test methods into test classes

Refactor test classes

---

ptvsd/pydevd_hooks.py
tests/system_tests/__init__.py
tests/system_tests/test_basic.py

(fixes #592)
Under certain circumstances, `__main__` is a "builtin" module.  Such modules do not have a `__file__` attribute.  Consequently, this caused the pydevd injection code to fail.  This PR fixes that.

Do not check __main__.__file__ under -m.

---

ptvsd/daemon.py
ptvsd/wrapper.py
tests/helpers/pydevd/_binder.py

This reverts commit bd390322a8e31dcdb318da95e108c82f7f3a4f97.
Fixes #633 
Fixes #618 
@ericsnowcurrently 
I'm revering the above commit, as it didn't fix anything and it was introduced with an assumption that it was the right way to do things. There was no change to any tests, hence there was no difference, the original bug #530 was not resolved, and we have a two new issues as a result. Hence reverting it.

Revert "Use sys.exit() instead of os.kill(). (#538)"

---

tests/helpers/debugclient.py
tests/helpers/proc.py
tests/helpers/pydevd/_binder.py
tests/highlevel/__init__.py
tests/highlevel/test_live_pydevd.py
tests/system_tests/__init__.py

* Add timeouts for thread.joins (**this is the main change**)
* Format errors captured and displayed (for py27 and 3 compatibility)
* Format code (this accounts for 95% of the changes, was tired of linter errors, hence formatted code using autpep8)

Add timeouts for thread.joins to ensure it does not block indefinitely

---

ptvsd/_remote.py
ptvsd/attach_server.py
ptvsd/daemon.py
ptvsd/pydevd_hooks.py
ptvsd/wrapper.py
tests/helpers/debugadapter.py
tests/helpers/debugsession.py
tests/helpers/script.py
tests/resources/system_tests/test_forever/attach_forever.py
tests/system_tests/__init__.py
tests/system_tests/test_enable_attach.py
tests/system_tests/test_main.py
tests/system_tests/test_remote.py

(helps #545)
We move the settrace() into a thread, but make sure to wait for the thread to finish in wait_for_attach().
My only concern with the solution is that the current thread will not get debugged if `enable_attach()` is called but `wait_for_attach()` is not (and no attach happens right away).  I'm going to address this in a follow-up PR by monkey-patching `sys.settrace` temporarily.

Do not wait for settrace() to finish until wait_for_attach().

---

tests/resources/system_tests/test_misc/single_thread.py
tests/resources/system_tests/test_misc/three_threads.py
tests/system_tests/test_misc.py

Add thread count tests

---

ptvsd/_remote.py
ptvsd/attach_server.py
ptvsd/daemon.py
ptvsd/pydevd_hooks.py
ptvsd/wrapper.py
tests/__init__.py
tests/helpers/debugadapter.py
tests/helpers/debugsession.py
tests/helpers/script.py
tests/resources/system_tests/test_forever/attach_forever.py
tests/system_tests/__init__.py
tests/system_tests/test_enable_attach.py
tests/system_tests/test_main.py
tests/system_tests/test_remote.py

(helps #545)
This reverts commit 80d86b961d2e548303aa59ec55b86801bbb50542.
Note that this still suffers from the caveat that if attach doesn't happen within a second (and `wait_for_attach()` isn't called) then the main thread will never have debugging enabled.  One way or another that will need to be addressed.

WIP: Revert "Revert "Do not wait for settrace() to finish until wait_for_attach(). (#628)" (#666)"

---

ptvsd/_vendored/pydevd/_pydev_bundle/pydev_console_utils.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info_regular.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py
ptvsd/_vendored/pydevd/pydevd.py
ptvsd/_vendored/pydevd/pydevd_tracing.py
ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_get_thread_stack.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_remote.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_remote_1.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_remote_unhandled_exceptions.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_remote_unhandled_exceptions2.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_suspend_policy.py
ptvsd/_vendored/pydevd/tests_python/test_additional_thread_info.py
ptvsd/_vendored/pydevd/tests_python/test_debugger.py
ptvsd/_vendored/pydevd/tests_python/test_null.py

Note: built upon https://github.com/Microsoft/ptvsd/pull/671 to avoid conflicts (so, that one has to be merged first).
Changes can be seen at commit: https://github.com/Microsoft/ptvsd/commit/564135748e40b39680f42b70077c18ee481d774f (note that it has some test changes along to fix some flakiness on pydevd tests on travis).

Fix 72 break suspension policy

---

ptvsd/wrapper.py

Fixes #707
Issue - parameter was being assigned to and the value was different in subsequent loops.
I'd say we need better linter rules, to ensure parameters are never assigned to. Generally considered a bad practice.

Remove unwanted parameter and re-assigning of it

---

ptvsd/wrapper.py
tests/highlevel/__init__.py
tests/highlevel/test_live_pydevd.py
tests/highlevel/test_messages.py
tests/system_tests/test_main.py

This change does the following:
1. Enables the suspend all policy
2. Pause/continue will always suspend or resume all threads
3. Stack trace request uses CMD_GET_THREAD_STACK
4. exception info is extracted on request.
This should address most of the concerns with #72.

Turning suspend all policy and using get stack trace command

---

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_breakpoints.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch_regular.py
ptvsd/_vendored/pydevd/pydevd.py
ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_exceptions.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_unhandled_exceptions.py
ptvsd/_vendored/pydevd/tests_python/test_debugger.py

Other changes in the pull request:
- Rename: break_on_exceptions_thrown_in_same_context -> skip_on_exceptions_thrown_in_same_context.
- Make sure that __exception__ is removed when resuming.

Properly add __exception__ on all frames on caught exceptions (fixes #679)

---

ptvsd/_vendored/force_pydevd.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py
ptvsd/_vendored/pydevd/pydev_sitecustomize/sitecustomize.py
ptvsd/_vendored/pydevd/pydevd.py
ptvsd/_vendored/pydevd/tests_python/debugger_fixtures.py
ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
ptvsd/_vendored/pydevd/tests_python/performance_check.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_breakpoint.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_breakpoint_remote.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_breakpoint_remote_no_import.py
ptvsd/_vendored/pydevd/tests_python/test_debugger.py
tests/resources/system_tests/test_break_into_debugger/attach_test_breakpoint.py
tests/resources/system_tests/test_break_into_debugger/launch_test_breakpoint.py
tests/resources/system_tests/test_break_into_debugger/mypkg_launch_breakpoint/__main__.py
tests/resources/system_tests/test_break_into_debugger/mypkg_reattach_breakpoint/__main__.py
tests/resources/system_tests/test_break_into_debugger/reattach_test_breakpoint.py
tests/system_tests/test_break_into_debugger.py

Some notes:
The `breakpoint()` builtin maps to `ptvsd.break_into_debugger()`. It's binds to `sys.breakpointhook` in Python 3.7 and to a `breakpoint()` builtin on earlier versions.
I decided not using the environment variable to be able to provide a fallback on earlier versions (and to work even if the PYTHONPATH is changed and no longer has access to the debugger).
Note that the version on `pydevd` connects to a host to do remote debugging if it's still not connected, but for `ptvsd` it's a requirement that the user is already connected (so, either he should've started with debugging or the `ptvsd.enable_attach`, `ptvsd.wait_for_attach` needs to be used -- as is expected from `ptvsd.break_into_debugger()`).
-- also, this pull request also adds a reorganization I did to use less …

Fix 253 builtin breakpoint

---

tests/resources/system_tests/test_disconnect/disconnect_test.py
tests/resources/system_tests/test_disconnect/mypkg/__main__.py
tests/system_tests/test_disconnect.py

Fixes #708 
Found a few new issues (fixes not in this PR):
1. `break_into_debugger` does not work in Server Attach mode, i,e., `python -m ptvsd --port 5678 --server test.py` #742
2. Launch with disconnect has test issues where disconnect request does not reach `ptvsd` #743

Add tests for continue on disconnect.

---

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py
ptvsd/wrapper.py

This is the first step to support json messages (to later address #45).
Will pause working on that to address other issues but it'd be nice to have that already integrated.
Also, this fixes an issue where enabling debug info (with a `PYDEV_DEBUG=True` env var) triggered a recursion of debug messages when the output was redirected (which is always the case for `ptvsd`).

Create command to enable pydevd to send data using http-procotol instead of by line with urllib quoting.

---

ptvsd/__main__.py
ptvsd/_local.py
ptvsd/_remote.py
ptvsd/_util.py
ptvsd/daemon.py
ptvsd/exit_handlers.py
ptvsd/pydevd_hooks.py
ptvsd/session.py
ptvsd/socket.py
tests/helpers/debugadapter.py
tests/helpers/debugclient.py
tests/helpers/debugsession.py
tests/ptvsd/test___main__.py
tests/system_tests/test_connection.py

Add --wait command line argument, and don't block code execution if it is not specified.

Fix #355: Add 'remote launch' - launch a program for remote debugging but continue running the user code

---

ptvsd/_vendored/pydevd/.travis.yml
ptvsd/_vendored/pydevd/.travis_install_jython_deps.sh
ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py
ptvsd/_vendored/pydevd/tests/test_jysimpleTipper.py
ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case4.py
ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_suspend_all.py
ptvsd/_vendored/pydevd/tests_python/test_debugger.py

With this request it's possible to pass `*` in `CMD_THREAD_SUSPEND` and `CMD_THREAD_RUN` to signal all threads should be suspended/resumed.

Provide a way to suspend and resume all threads. Fixes #732

---

ptvsd/wrapper.py
tests/highlevel/test_messages.py

Switch to using suspend-all/resume-all command

---

ptvsd/debugger.py

Add ability to run without debugging

---

ptvsd/__main__.py
ptvsd/_attach.py
ptvsd/_remote.py
ptvsd/attach_server.py

Add --pid option to ptvsd command line. When used, injects the debugger into the process with the specified ID, such that it connects back to the specified host/port.

Fix #200: Local attach

---

ptvsd/wrapper.py

Detaching from a VSCode debug session via localhost:3000 on Windows 10 using the debug 'disconnect' button results in an unhandled exception in wrapper.py.
The specific unhandled error is errno.ECONNRESET (10054)
When this exception is not handled correctly, the instance of ptvsd becomes unresponsive and does not allow the debugger to connect again.
Notes:
This change fixes this issue but I can see that convert_eof() in socket.py should be handling this error and raising an EOFError exception - but for some reason it's not and a socket.error with errno == 10054 is raised instead.

Added handling of unhandled exception generated when VS Code disconnects

---

.flake8
.gitignore
.pylintrc
.travis.yml
.vscode/settings.json
Makefile
ptvsd.code-workspace
ptvsd/compat.py
ptvsd/messaging.py
ptvsd/wrapper.py
pytests/__init__.py
pytests/func/__init__.py
pytests/helpers/__init__.py
pytests/helpers/jsonre.py
pytests/helpers/test_jsonre.py
pytests/pytest.ini
pytests/test_messaging.py
setup.cfg
setup.py

Add new JSON IPC implementation to be shared between the product and the tests.
Add pytest-based test support, and wire it up to setup.py and Travis.
Dial pylint down to complain about important things only.
Various minor fixes exposed by pylint.
Fixes #831.

Test & infrastructure cleanup, stage 1

---

ptvsd/wrapper.py

I don't know if this solves all the compatibility issues for this issue #210.
But with this fix, this problem is solved, and I was able to fully debug my code in Python version 3.3.5 https://github.com/Microsoft/ptvsd/issues/828

Fix debugging on Python 3.3.5

---

ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py
ptvsd/_vendored/pydevd/tests_python/test_in_project_roots.py

Note that I haven't actually changed `ptvsd` not to issue `CMD_SET_PROJECT_ROOTS` as many tests have to be updated and I saw that there's a pull request open related to that. 
I'm still a little unsure if this is actually the root cause for #854 as from my tests the location mentioned on it (`/Users/vsts/Library/Python/3.7/lib/python/site-packages`) already seemed to be treated as a library, so, it's possible this still doesn't fix the root cause (although I think it's a step in the right direction anyways and it should handle `/usr/local/lib/python3.7/site-packages` which wasn't really there and I could not find out a better heuristic to find about it).

Make sure that any folder ending with site-packages is considered a library. Fixes #854

---

README.md

this fixes the json comments being highlighted as error in README.md

fix json comments syntax highlight

---

ptvsd/compat.py
pytests/__init__.py
pytests/conftest.py
pytests/func/test_multiproc.py
pytests/func/test_run.py
pytests/helpers/__init__.py
pytests/helpers/colors.py
pytests/helpers/messaging.py
pytests/helpers/pattern.py
pytests/helpers/session.py
pytests/helpers/test_timeline.py
pytests/helpers/timeline.py
pytests/helpers/watchdog.py
pytests/requirements.txt
setup.py
test_requirements.txt

- implicit freezing on wait
- wait_for_next() and expect_new()
- unobserved occurrences checking
- timeline slicing into intervals
- queue-based timeline for accurate timestamps
- finer-grained timeline tests
- capture ptvsd stderr/stdout and timestamp it
- tighten up ptvsd tests (check more)
- pretty colors!

Refactor timeline

---

ptvsd/messaging.py

Register the request before sending the message that corresponds to it.

Fix #894: Race condition in JsonMessageChannel

---

ptvsd/__main__.py
tests/helpers/debugadapter.py
tests/ptvsd/test___main__.py

Remove --server-host. Server mode is always implied by default now in all circumstances, and --client is used to specify client mode.

Fix #896: Changes in CLI arguments between versions

---

ptvsd/socket.py
pytests/test_socket.py

Fixes #912, #949
@int19h is the try/catch the right way to do this? Do we need to create a new socket in place of `pass`?

Set SIO_LOOPBACK_FAST_PATH while creating socket in windows

---

ptvsd/wrapper.py

Avoid hogging CPU while waiting on the subprocess notification queue.

Fix #967: Debugging Django in VSC with subprocess debugging is very slow

---

ptvsd/__main__.py
ptvsd/multiproc.py
ptvsd/options.py
pytests/helpers/session.py

Use parent's --host when spawning child processes.

Fix #984: Remote debugging not working with multiproc

---

ptvsd/wrapper.py
pytests/func/test_breakpoints.py
pytests/func/testfiles/bp/a&b/test.py

 Stacktrace contains xml escaped characters. Fix #948, #981

---

pytests/func/test_breakpoints.py
pytests/func/test_django.py
pytests/func/test_evaluate.py
pytests/func/test_exception.py
pytests/func/test_flask.py
pytests/func/test_path_mapping.py
pytests/func/test_vs_specific.py
pytests/helpers/pathutils.py
pytests/helpers/pattern.py
src/ptvsd/wrapper.py

Fix #874: Watch window freezes the system when Name contains non-ASCII symbols
Fix #1064: test_module_events is failing on Windows
Use Unicode literals throughout wrapper.py, and fix pathname handling.
Add evaluation test for Unicode character in an expression.
Fix path pattern such that its __eq__ is used deterministically.

Fix #874, #1064

---

src/ptvsd/pathutils.py
src/ptvsd/wrapper.py

Fix #1037: Setting breakpoint fails on Python files containing non-ASCII characters
Fix #1066: Fetching remote source for a file with a Unicode name fails on 2.7

More Unicode fixes: #1037, #1066

---

src/ptvsd/__main__.py

Add '' to sys.path for -m and -c.
Make sure that sys.argv is properly updated by main(), even if input is a different list.

Fix #1108: Launch module from VSC broken in master

---

pytest.ini
test_requirements.txt
tests/func/test_django.py
tests/func/test_flask.py
tests/helpers/__init__.py
tests/helpers/session.py

Use pytest-xdist to speed up tests and continue running after timeout.

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py
src/ptvsd/_vendored/pydevd/tests_python/debugger_fixtures.py
src/ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger.py

Pass 'removed' instead of 'remove' to on_breakpoints_changed. #1118

---

pytest.ini
src/ptvsd/wrapper.py
tests/helpers/session.py

This doesn't fix everything, but at least the 2.7 Windows run is passing now. And remaining failures in 3.x runs don't appear to be related to these fixes, so I'd like to get them in first.

Assorted test fixes for the Azure automated test run.

---

tests/func/test_breakpoints.py

See https://github.com/Microsoft/ptvsd/issues/1124#issuecomment-459506802 for a detailed explanation

Disable test_path_with_unicode for Python 3.5 per #1124

---

src/ptvsd/wrapper.py

Do not allow 'setBreakpoints' request until either 'launch' or 'attach' request is received.
Wait for 'launch' or 'attach' request to process path mappings before handling 'setBreakpoints'.

Fix #1093: breakpoint are not hit when debugger is attached to remote target

---

src/ptvsd/_util.py
src/ptvsd/wrapper.py
test_requirements.txt
tests/func/test_breakpoints.py
tests/helpers/__init__.py
tests/helpers/session.py

When setting breakpoints, validate line numbers against dis.findlinestarts() for the given file.

Fix #206: Validate breakpoint targets

---

.env
.gitignore
ptvsd.code-workspace

With these changes, VSC test discovery works on ptvsd tests, provided that all the test requirements are manually installed (`pip install -r test_requirements.txt`) for the selected Python interpreter.

Enable discovery of ptvsd tests in VSCode

---

src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_import_hook.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger.py

This is a backport of the fix for https://www.brainwy.com/tracker/PyDev/975 (it was a community-provided pull request for pydevd).

PyDev console hooks causes incompatibility with imports matplotlib and pylab. Fix for PyDev-975

---

src/ptvsd/__main__.py
src/ptvsd/_vendored/pydevd/pydevd.py
src/ptvsd/multiproc.py

Gracefully handle failures when flushing potentially closed standard streams on exit.
Add more multiprocess logging, and fix sys.argv logging.

Fix #1165: Detaching sometimes throws ValueError: I/O operation on closed file

---

src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_monkey.py
src/ptvsd/log.py
tests/func/test_multiproc.py

Re-implement argument quoting on Windows in accordance with
https://docs.microsoft.com/en-us/windows/desktop/api/shellapi/nf-shellapi-commandlinetoargvw

Fix #1227: subprocess arguments incorrectly escaped inside the debugger

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_filtering.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
src/ptvsd/_vendored/pydevd/pydevd_file_utils.py
src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_source_reference.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py
src/ptvsd/_vendored/pydevd/tests_python/test_pydevd_filtering.py
src/ptvsd/wrapper.py

Also adds `linecache` fallback and a different approach to handling `<...>` as discussed in #1232.

Fix #1173: Gracefully handle I/O errors when processing source request 

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/__main__pydevd_gen_debug_adapter_protocol.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_base_schema.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_schema.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py
src/ptvsd/_vendored/pydevd/tests_python/test_schema.py
tests/func/test_django.py
tests/func/test_evaluate.py
tests/func/test_flask.py
tests/helpers/pattern.py

The approach I decided to take is to add the translation support to the schema so that when serializing/deserializing messages the translation is done automatically (the particular places are `NetCommand.__init__` and `_PyDevJsonCommandProcessor.process_net_command_json`).
This was a bit more work than manually doing it at the needed places but in the future when we translate the `threadId` it should use the same recipe.

Make sure that DAP ids are int32. Fixes #1251

---

src/ptvsd/wrapper.py

Fixes #1266. We previously treated this as a notify (event) to pydevd, with the switch to json protocol this is now a request. If we wait for a response for request such as `continue` request. The thread could begin and suspend immediately.
This could be done with `pydevd_notify`, notify calls don't expect a response. since requests like continue has a response this causes additional issue in the debugger where it fails to associate the response with a request, and crash.
In this PR, I am replicating the same behavior as we had with `pydevd_notify` by using `pydevd_request` but ignoring the response.

Remove 'yield' from some request handlers

---

ptvsd.code-workspace
src/ptvsd/__main__.py
tests/func/test_run.py
tests/func/testfiles/testpkgs/pkg1/sub/__main__.py

Add sys.path entry for current directory before using runpy/importlib to resolve the module.

Fix #1272: Launch a SubModule

---

src/ptvsd/__main__.py

This fixes the `AssertionError: Having a single quote messes with our command.` error cited here #863.
I then have a the same traceback as here #1239.

Fix single quote issue during process attach

---

src/ptvsd/ipcjson.py

Use threading instead of thread for IpcChannel, and do not defer its import.

Fix #1307: Module name conflict while debugging with -m

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_large_exception_stack.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py
tests/func/test_exception.py
tests/helpers/session.py

`maxExceptionStackFrames: 5` in launch json should limit the number of frames to 5, lines to ~10. The exact number of lines depends on the stack situation. Default is all frames, this has to be the default to support VS style exception info UI. Since VS did not have this setting and adding a setting there is non trivial.

Add setting to limit number of lines in stack for exception details. Fixes #582

---

src/ptvsd/_vendored/pydevd/.travis_install_python_deps.sh
src/ptvsd/_vendored/pydevd/pydevd_plugins/django_debug.py
src/ptvsd/_vendored/pydevd/tests_python/debugger_fixtures.py
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/templates/my_app/inherited.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/templates/my_app/inherits.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/templates/my_app/no_var_error.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/templates/my_app/template_error.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/templates/my_app/template_error2.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/urls.py
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_17/my_app/views.py
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_21/my_app/templates/my_app/inherited.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_21/my_app/templates/my_app/inherits.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_21/my_app/templates/my_app/no_var_error.html
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_21/my_app/urls.py
src/ptvsd/_vendored/pydevd/tests_python/my_django_proj_21/my_app/views.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger.py

Django 2.2 tests and fixes for exception breakpoints in Django 1.7. Fixes #1298, #1294

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_breakpoints.py
src/ptvsd/_vendored/pydevd/pydevd.py

Treat breakpoints with `condition: ""` as non-conditional.

Fix #1296 SyntaxError for breakpoints with empty condition

---

src/ptvsd/_vendored/pydevd/pydevd.py
src/ptvsd/_vendored/pydevd/pydevd_tracing.py

I know ptvsd doesn't officially support IronPython, and I don't really know whether the DAP works with it as it's not currently in the ci -- not even in the `pydevd` ci, where currently I only take a look when someone complains, but with this change (using the `pydevd` protocol) it's working for a simple scenario (i.e.: hit breakpoints/step in/over), so, it's at least a step in the right direction.

Make it possible to use debugger in IronPython again.

---

src/ptvsd/_vendored/force_pydevd.py
src/ptvsd/_vendored/pydevd/_pydev_bundle/pydev_log.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch.py
src/ptvsd/_vendored/pydevd/_pydevd_frame_eval/pydevd_frame_eval_main.py
src/ptvsd/_vendored/pydevd/pydevd.py

With this change I'm also using an env variable to determine whether the cython compile command line should be shown so that the code on `pydevd` and `ptvsd` is the same.

Always send goto response

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
src/ptvsd/_vendored/pydevd/pydevd.py
src/ptvsd/_vendored/pydevd/tests_python/debugger_fixtures.py
src/ptvsd/_vendored/pydevd/tests_python/debugger_unittest.py
src/ptvsd/_vendored/pydevd/tests_python/resources/_debugger_case_wait_for_attach.py
src/ptvsd/_vendored/pydevd/tests_python/test_debugger_json.py

Some notes:
- I still haven't done changes in `ptvsd` (not sure if it's worth doing the needed monkeypatching vs going toward the final solution splitting `ptvsd` and `pydevd`).
- I created `_enable_attach` and `_wait_for_attach` as protected because they should only be public on `ptvsd`, not on `pydevd`.

Provide disconnect/reconnect and a non-blocking way of setting up the debugger. Fixes #1382, Fixes #1248.

---

src/ptvsd/adapter/__main__.py
src/ptvsd/adapter/channels.py
src/ptvsd/adapter/debuggee.py
src/ptvsd/adapter/messages.py
src/ptvsd/adapter/state.py
src/ptvsd/common/messaging.py
src/ptvsd/common/singleton.py
tests/func/test_break_into_dbg.py

Implements the main message loops for IDE and debug server communication channels, and framework for DAP message handlers.
Lays out scaffolding for debuggee process management and connectivity.
Implements generic message propagation between IDE and debug server.
Partially implements playback of the initialization sequence when debug server is connected (without validation).
Implements `initialize`, `disconnect`, and `terminate` DAP messages.
Partially implements `attach`, `launch`, and `configurationDone` DAP messages.

Fix #1486: Message processing/forwarding loop

---

src/ptvsd/_remote.py
src/ptvsd/attach_server.py

Users should be able to call enable attach with port `0` and have a way to get the port address.
```console
> import ptvsd
> ptvsd.enable_attach(('localhost', 0))
('loclahost', 58940)
```

Ensure port is set on enable_attach

---

README.md

There's a [*New home for the Debug Adapter Protocol*][1], so we might as well link to it.
[1]: https://code.visualstudio.com/blogs/2018/08/07/debug-adapter-protocol-website
P.S. Wow, they were not kidding about the old home being an obscure github repository: https://github.com/Microsoft/vscode-debugadapter-node manages to sound not only vscode-specific, but also like a Node-specific secondary implementation.  And who would suspect that the JSON schema is actually the source of truth?  I guess you guys knew, but I had no clue until I clicked through to Microsoft/vscode#19636 from the blog post.

Update Debug Adapter Protocol links

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/debugProtocolCustom.json
src/ptvsd/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_schema.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py

This Fixes #1523 in a way that it adds a custom event so that there is always a name for the event.
This also addresses Fixes #1497, Fixes #1496. Those events don't need additional work, and they can be forwarded in their current state.

Custom pydevd event to support InputRequested

---

.gitignore
src/ptvsd/common/fmt.py
src/ptvsd/common/messaging.py
src/ptvsd/common/stacks.py
tests/_logs/README
tests/debug.py
tests/pydevd_log.py
tests/pytest_fixtures.py
tests/pytest_hooks.py
tests/test_data/_PYTHONPATH/backchannel.py
tests/test_data/_PYTHONPATH/debug_me.py

Fix various bugs around handling of disconnect in JsonIOStream and JsonMessageChannel.
Fix handling of DAP "terminated" event in debug.Session.
Add --ptvsd-logs and --pydevd-logs switches to pytest.
Improve message logging to fully capture the raw message data in the logs if deserialization fails.
Log all debuggee environment variables in debug.Session, and improve log readability.

Fix #1551: Backchannel failures in tests

---

src/ptvsd/__init__.py

Preload codecs used by ptvsd and pydevd to avoid deadlocks when calling wait_for_attach()  while importing a module on Python 2.

Fix #1552: attach_socket_import tests hang waiting for "process" event

---

src/ptvsd/adapter/__main__.py
src/ptvsd/adapter/channels.py
src/ptvsd/adapter/messages.py

Fixes #1556
You should be able to connect tot the adapter using this CLI:
```
-m ptvsd.adapter --debug-port 6789
```
This launch json config:
```js
{
"name": "Attach port",
"type": "python",
"request": "attach",
"debugServer": 6789,
},
```

Add option to connect to adapter via port from IDE

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
tests/func/test_breakpoints.py
tests/func/test_exclude_rules.py

Fix for breakpoint binding issue in VS

---

src/ptvsd/common/messaging.py
tests/watchdog/__init__.py
tests/watchdog/worker.py

Close the watchdog message channel from the test process side after "stop" command is sent and acknowledged.

Fix #1614: Test run times out on Python 2.7

---

src/ptvsd/_vendored/pydevd/pydevd.py
src/ptvsd/adapter/messages.py
src/ptvsd/server/attach.py

Testing to see if this is a better solution. If this works out better i think we should remove the `dontTrace*Patterns` from setDebuggerProperty

Set don't trace patterns from the debug server

---

src/ptvsd/adapter/ide.py
src/ptvsd/adapter/server.py
tests/ptvsd/server/test_breakpoints.py

When using launcher to redirect output, tell pydevd to not perform redirection.
Always propagate "output" events from the server to the IDE.
Fix test_log_point to not assume that logpoint output is strictly ordered wrt regular output.

Fix #1769: Logpoint messages aren't printed for "launch"

---

sonar-project.properties

As it says. This doesn't include a project key as I am seeing if the Autoscan beta feature will "just work" https://sonarcloud.io/documentation/integrations/github/

Add sonar file.

---

src/ptvsd/adapter/session.py
tests/debug/session.py
tests/ptvsd/server/test_path_mapping.py
tests/ptvsd/server/test_start_stop.py
tests/pytest_fixtures.py

With these, all remaining failures are sporadic.

Final batch of test fixes / disabling before merging with master

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py
src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
src/ptvsd/adapter/ide.py
tests/debug/session.py

Updating telemetry and some comments

---

.sonarcloud.properties
sonar-project.properties
src/ptvsd/__init__.py
src/ptvsd/_vendored/pydevd/pydevd.py
src/ptvsd/adapter/__main__.py
src/ptvsd/server/api.py
tests/debug/comms.py

Reverse the connection direction used by enable attach internals.

---

src/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_api.py

Fix the ctypes definition of PROCESSENTRY32 to have the correct size on 64-bit Python.

Fix #1877: "pydevdSystemInfo" does not report "ppid" on Python 2.7 on Windows

---

src/ptvsd/_vendored/__init__.py

Iterate over a snapshot of sys.modules when checking loaded modules.

Fix #1888: Concurrent imports cause error in force_pydevd

---

src/ptvsd/_vendored/pydevd/pydevd.py
src/ptvsd/adapter/ide.py
src/ptvsd/adapter/servers.py
tests/debug/comms.py
tests/ptvsd/server/test_multiproc.py

Use "evaluate" request without "frameId" to import ptvsd into the debuggee as soon as server attaches.
Fix test_subprocess to use the new test API.

Fix #1875: Inject ptvsd into subprocesses

---

pytest.ini
src/ptvsd/adapter/ide.py
src/ptvsd/common/log.py
src/ptvsd/common/sockets.py
src/ptvsd/launcher/adapter.py
src/ptvsd/launcher/debuggee.py
tests/debug/comms.py
tests/debug/runners.py
tests/patterns/some.py
tests/ptvsd/common/test_socket.py
tests/ptvsd/server/test_args.py
tests/ptvsd/server/test_attach.py
tests/ptvsd/server/test_breakpoints.py
tests/ptvsd/server/test_disconnect.py
tests/ptvsd/server/test_exception.py
tests/ptvsd/server/test_exclude_rules.py
tests/ptvsd/server/test_flask.py
tests/ptvsd/server/test_justmycode.py
tests/ptvsd/server/test_multiproc.py
tests/ptvsd/server/test_output.py
tests/ptvsd/server/test_path_mapping.py
tests/ptvsd/server/test_source_mapping.py
tests/ptvsd/server/test_start_stop.py
tests/ptvsd/server/test_stop_on_entry.py
tests/ptvsd/server/test_threads.py
tests/pytest_fixtures.py
tests/watchdog/worker.py

- reduce test matrix where not necessary
- switch to `sys.platform`

Reduce running time for CI test runs

---

.vscode/launch.json
src/ptvsd/adapter/ide.py
src/ptvsd/adapter/launchers.py
src/ptvsd/adapter/servers.py
src/ptvsd/common/sockets.py

For "launch", match processes on parent PID as a fallback for PID, to accommodate launcher stubs like py.exe.

Fix #1930: "launch" doesn't work with venv on Windows and Python 3.7+

---

src/ptvsd/adapter/ide.py
src/ptvsd/adapter/launchers.py

Do not validate PID of the debuggee when debug server connects while handling "launch".
Restrict "launch" to the first session with no server connections.

Fix #1944: Debugging fails with timeout when using conda run

---

src/ptvsd/common/json.py
src/ptvsd/common/messaging.py

Use fmt() instead of format() for validation error text.
Include description of message that was deemed invalid due to validation in the error text.

Fix #1950: Nonsensical error message for type errors in launch.json

---

.travis.yml
src/ptvsd/launcher/__main__.py

Ignore SIGINT in ptvsd.launcher.

Fix #1896: Using Ctrl+C causes launcher to print traceback

---

.vscode/launch.json
src/ptvsd/adapter/__main__.py
src/ptvsd/common/sockets.py
src/ptvsd/server/api.py

Close stdin, stdout, and stderr in the adapter.
Double-fork() and setsid() on Unix to daemonize properly.
Use CREATE_NEW_PROCESS_GROUP and CREATE_NO_WINDOW on Win32 to daemonize properly.

Fix #2004: Adapter process is not fully detached from parent server

---

src/ptvsd/adapter/launchers.py
src/ptvsd/adapter/servers.py
src/ptvsd/common/messaging.py
src/ptvsd/launcher/debuggee.py

This also fixes the error "unbound method ...", as seen in e.g. #1978, that could occur while reporting errors during launch, and another one when reporting error to inject debugger for attach-by-PID.

Fix #2008 and other error reporting issues
